openapi: 3.0.3
info:
    title: Publish API
    description: Publish API
    contact:
        name: WuHui Zuo
        url: https://github.com/wuhuizuo
        email: wuhui.zuo@pingcap.com
    version: 1.0.0
servers:
    - url: http://0.0.0.0:80
paths:
    /fs/publish-request:
        post:
            tags:
                - fileserver
            summary: request-to-publish fileserver
            operationId: fileserver#request-to-publish
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeliveryByRulesRequestBody'
                        example:
                            artifact_url: Velit praesentium est.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                                    description: Request id for async mode (uuidv4 format)
                                    example: 619899f7-e1fb-46ae-b91a-95bb1cad368f
                                    format: uuid
                                description: request track ids
                                example:
                                    - 93d12938-8429-4c45-bbbb-bbdac12114db
                                    - 71600dd6-34b6-4427-97be-1fdfbe8c4079
                                    - 33d5cab4-d23f-42ec-b4dd-68330a3469b0
                                    - b300c564-e1f1-4486-8963-98c3840fa15f
                            example:
                                - 06482452-1444-42db-b941-a8fcd3e8022e
                                - cfa9e6da-69b0-4c38-8fe7-82eb246847c4
                                - 34165ab9-29b3-4fa4-b2a8-442f429f346f
    /fs/publish-request/{request_id}:
        get:
            tags:
                - fileserver
            summary: query-publishing-status fileserver
            operationId: fileserver#query-publishing-status
            parameters:
                - name: request_id
                  in: path
                  description: Request id for async mode (uuidv4 format)
                  required: true
                  schema:
                    type: string
                    description: Request id for async mode (uuidv4 format)
                    example: 109aed2d-2709-45cf-869d-ba12f27a9f4d
                    format: uuid
                  example: f7a3c282-8bfe-475e-a91a-150660cd3e08
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: State of the task
                                example: success
                                enum:
                                    - queued
                                    - processing
                                    - success
                                    - failed
                                    - canceled
                            example: success
    /image/collect-multiarch:
        post:
            tags:
                - image
            summary: request-multiarch-collect image
            operationId: image#request-multiarch-collect
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RequestMultiarchCollectRequestBody'
                        example:
                            async: false
                            image_url: Voluptatibus quas aut.
                            release_tag_suffix: Dolor deleniti id earum.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/RequestMultiarchCollectResponseBody'
                            example:
                                async: false
                                repo: Ipsam id ipsa.
                                request_id: e8c6ec54-d74c-4516-a8de-88ec9a45e2ab
                                tags:
                                    - Saepe sapiente non ea.
                                    - Nemo deserunt sint et.
    /image/collect-multiarch/{request_id}:
        get:
            tags:
                - image
            summary: query-multiarch-collect-status image
            operationId: image#query-multiarch-collect-status
            parameters:
                - name: request_id
                  in: path
                  description: Request id for async mode (uuidv4 format)
                  required: true
                  schema:
                    type: string
                    description: Request id for async mode (uuidv4 format)
                    example: 0809e0b1-395d-466e-b8f6-03289da521c4
                    format: uuid
                  example: 96e94dc3-1425-40c1-861c-2b609349dc3c
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: State of the task
                                example: queued
                                enum:
                                    - queued
                                    - processing
                                    - success
                                    - failed
                                    - canceled
                            example: queued
    /image/copy:
        post:
            tags:
                - image
            summary: request-to-copy image
            operationId: image#request-to-copy
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RequestToCopyRequestBody'
                        example:
                            destination: Sit pariatur quis id sunt dignissimos accusantium.
                            source: Et sed doloremque officiis accusantium ab.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: Request id for async mode (uuidv4 format)
                                example: 9532f472-eac2-4b1f-9631-fa57fdb9d45e
                                format: uuid
                            example: d4688f79-0eff-46b1-8181-8ec139086c90
    /image/copy/{request_id}:
        get:
            tags:
                - image
            summary: query-copying-status image
            operationId: image#query-copying-status
            parameters:
                - name: request_id
                  in: path
                  description: Request id for async mode (uuidv4 format)
                  required: true
                  schema:
                    type: string
                    description: Request id for async mode (uuidv4 format)
                    example: 9fd369e1-04e3-4c64-94fb-b062f569a159
                    format: uuid
                  example: 85d714b0-1f72-43eb-a783-143bf8971bed
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: State of the task
                                example: queued
                                enum:
                                    - queued
                                    - processing
                                    - success
                                    - failed
                                    - canceled
                            example: queued
    /tidbcloud/devops/cloudconfig/versions/component:
        post:
            tags:
                - tidbcloud
            summary: update-component-version-in-cloudconfig tidbcloud
            operationId: tidbcloud#update-component-version-in-cloudconfig
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateComponentVersionInCloudconfigRequestBody'
                        example:
                            image: xxx.com/component:v26.3.1-nextgen
                            stage: prod
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UpdateComponentVersionInCloudconfigResponseBody'
                            example:
                                stage: Animi recusandae.
                                tickets:
                                    - change_id: Quibusdam quibusdam veniam nisi rerum.
                                      component: Omnis autem sequi.
                                      component_version: Fuga occaecati.
                                      id: Omnis iste ratione doloremque.
                                      release_id: Saepe necessitatibus veritatis ipsa qui unde.
                                      url: http://glover.biz/corine
                                    - change_id: Quibusdam quibusdam veniam nisi rerum.
                                      component: Omnis autem sequi.
                                      component_version: Fuga occaecati.
                                      id: Omnis iste ratione doloremque.
                                      release_id: Saepe necessitatibus veritatis ipsa qui unde.
                                      url: http://glover.biz/corine
    /tidbcloud/devops/kernel-images/build-callback:
        post:
            tags:
                - tidbcloud
            summary: request-sync-kernel-image tidbcloud
            description: Request to sync kernel image via ops platform kernel image build callback
            operationId: tidbcloud#request-sync-kernel-image
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RequestSyncKernelImageRequestBody'
                        example:
                            image: us.gcr.io/pingcap-public/tidbx/tikv:v8.5.4-nextgen.202510.31
                            stage: dev
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: request sync result message
                                example: Omnis sed repudiandae aut.
                            example: Nostrum dolores illum et.
    /tidbcloud/tidbx-component-image-builds:
        post:
            tags:
                - tidbcloud
            summary: add-tidbx-image-tag-in-tcms tidbcloud
            operationId: tidbcloud#add-tidbx-image-tag-in-tcms
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddTidbxImageTagInTcmsRequestBody'
                        example:
                            github:
                                commit_sha: 031069dfc0c70e839d996c9e1cf3d34930fc662f
                                full_repo: pingcap/tidb
                                ref: refs/heads/master
                            image: xxx.com/component:v26.3.1-nextgen
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AddTidbxImageTagInTcmsResponseBody'
                            example:
                                branch: v26.3.1
                                imageTag: v26.3.1-nextgen
                                repo: pingcap/tidb
                                sha: 031069dfc0c70e839d996c9e1cf3d34930fc662f
    /tiup/delivery-by-rules:
        post:
            tags:
                - tiup
            summary: delivery-by-rules tiup
            description: Request to delivery TiUP packages from OCI artifact controlled by delivery rules
            operationId: tiup#delivery-by-rules
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeliveryByRulesRequestBody'
                        example:
                            artifact_url: oci.com/repo:tag
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                                    example: Unde et ut et earum.
                                description: request track ids
                                example:
                                    - Ducimus minus facilis nihil sunt odit.
                                    - Et modi voluptatem expedita.
                            example:
                                - Voluptas voluptatibus nemo.
                                - Earum corrupti enim exercitationem eum voluptatem.
    /tiup/publish-request:
        post:
            tags:
                - tiup
            summary: request-to-publish tiup
            description: Request to publish TiUP packages from a OCI artifact
            operationId: tiup#request-to-publish
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RequestToPublishRequestBody'
                        example:
                            artifact_url: oci.com/repo:tag
                            tiup_mirror: staging
                            version: v1.0.0
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                                    example: Facilis sequi quas officia distinctio.
                                description: request track ids
                                example:
                                    - Voluptatum sint excepturi voluptatem pariatur.
                                    - Voluptatum ut eius rerum.
                                    - Officia labore nulla.
                            example:
                                - Ex ipsum aspernatur quod deleniti fugit.
                                - Temporibus illum dolorum sed.
                                - Provident esse quia id perferendis dolores.
                                - Et voluptatum ex quod dolores fugit voluptas.
    /tiup/publish-request-single:
        post:
            tags:
                - tiup
            summary: request-to-publish-single tiup
            description: Request to publish a single TiUP package from a binary tarball
            operationId: tiup#request-to-publish-single
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PublishRequestTiUP'
                        example:
                            from:
                                http:
                                    url: https://example.com/tidb-v7.5.0-linux-amd64.tar.gz
                                type: http
                            publish:
                                arch: amd64
                                description: TiDB GA
                                entry_point: bin/tidb-server
                                name: tidb
                                os: linux
                                standalone: false
                                version: v7.5.0
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: Request id for async mode (uuidv4 format)
                                example: bcaba5d4-76d9-4c5f-8c49-d2f168b145b4
                                format: uuid
                            example: 50ea094a-08ac-4604-aa09-32d380266040
    /tiup/publish-request/{request_id}:
        get:
            tags:
                - tiup
            summary: query-publishing-status tiup
            operationId: tiup#query-publishing-status
            parameters:
                - name: request_id
                  in: path
                  description: request track id
                  required: true
                  schema:
                    type: string
                    description: request track id
                    example: Impedit nostrum.
                  example: Vero aut voluptates voluptates fuga debitis.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: State of the task
                                example: success
                                enum:
                                    - queued
                                    - processing
                                    - success
                                    - failed
                                    - canceled
                            example: success
    /tiup/reset-rate-limit:
        post:
            tags:
                - tiup
            summary: reset-rate-limit tiup
            operationId: tiup#reset-rate-limit
            responses:
                "200":
                    description: OK response.
components:
    schemas:
        AddTidbxImageTagInTcmsRequestBody:
            type: object
            properties:
                github:
                    type: object
                    properties:
                        commit_sha:
                            type: string
                            description: full commit SHA
                            example: 031069dfc0c70e839d996c9e1cf3d34930fc662f
                            minLength: 40
                            maxLength: 40
                        full_repo:
                            type: string
                            description: full github repo name
                            example: pingcap/tidb
                        ref:
                            type: string
                            description: git ref
                            example: refs/heads/master
                    description: git informations
                    example:
                        commit_sha: 031069dfc0c70e839d996c9e1cf3d34930fc662f
                        full_repo: pingcap/tidb
                        ref: refs/heads/master
                    required:
                        - full_repo
                        - commit_sha
                image:
                    type: string
                    description: container image with tag
                    example: xxx.com/component:v26.3.1-nextgen
            example:
                github:
                    commit_sha: 031069dfc0c70e839d996c9e1cf3d34930fc662f
                    full_repo: pingcap/tidb
                    ref: refs/heads/master
                image: xxx.com/component:v26.3.1-nextgen
            required:
                - image
        AddTidbxImageTagInTcmsResponseBody:
            type: object
            properties:
                branch:
                    type: string
                    description: github branch or tag name
                    example: v26.3.1
                imageTag:
                    type: string
                    description: image tag
                    example: v26.3.1-nextgen
                repo:
                    type: string
                    description: github full repo
                    example: pingcap/tidb
                sha:
                    type: string
                    description: github commit sha in the repo
                    example: 031069dfc0c70e839d996c9e1cf3d34930fc662f
            example:
                branch: v26.3.1
                imageTag: v26.3.1-nextgen
                repo: pingcap/tidb
                sha: 031069dfc0c70e839d996c9e1cf3d34930fc662f
        DeliveryByRulesRequestBody:
            type: object
            properties:
                artifact_url:
                    type: string
                    description: The full url of the pushed OCI artifact, contain the tag part. It will parse the repo from it.
                    example: oci.com/repo:tag
            example:
                artifact_url: oci.com/repo:tag
            required:
                - artifact_url
        From:
            type: object
            properties:
                http:
                    $ref: '#/components/schemas/FromHTTP'
                oci:
                    $ref: '#/components/schemas/FromOci'
                type:
                    type: string
                    example: http
                    enum:
                        - oci
                        - http
            example:
                http:
                    url: https://example.com/tidb-v7.5.0-linux-amd64.tar.gz
                type: http
            required:
                - type
        FromHTTP:
            type: object
            properties:
                url:
                    type: string
                    example: https://example.com/tidb-v7.5.0-linux-amd64.tar.gz
            description: Source from a direct HTTP URL
            example:
                url: https://example.com/tidb-v7.5.0-linux-amd64.tar.gz
            required:
                - url
        FromOci:
            type: object
            properties:
                file:
                    type: string
                    example: tidb-v7.5.0-linux-amd64.tar.gz
                repo:
                    type: string
                    example: hub.pingcap.net/dev/ci/tidb
                tag:
                    type: string
                    example: v7.5.0_linux_amd64
            description: Source from an OCI artifact
            example:
                file: tidb-v7.5.0-linux-amd64.tar.gz
                repo: hub.pingcap.net/dev/ci/tidb
                tag: v7.5.0_linux_amd64
            required:
                - repo
                - tag
                - file
        PublishInfoTiUP:
            type: object
            properties:
                arch:
                    type: string
                    example: amd64
                description:
                    type: string
                    example: TiDB GA
                entry_point:
                    type: string
                    example: bin/tidb-server
                name:
                    type: string
                    example: tidb
                os:
                    type: string
                    example: linux
                standalone:
                    type: boolean
                    example: false
                version:
                    type: string
                    example: v7.5.0
            example:
                arch: amd64
                description: TiDB GA
                entry_point: bin/tidb-server
                name: tidb
                os: linux
                standalone: false
                version: v7.5.0
            required:
                - name
                - os
                - arch
                - version
        PublishRequestTiUP:
            type: object
            properties:
                from:
                    $ref: '#/components/schemas/From'
                publish:
                    $ref: '#/components/schemas/PublishInfoTiUP'
                tiup_mirror:
                    type: string
                    description: '`staging` is http://tiup.pingcap.net:8988, `prod` is http://tiup.pingcap.net:8987.'
                    default: staging
                    example: staging
                    enum:
                        - staging
                        - prod
            example:
                from:
                    http:
                        url: https://example.com/tidb-v7.5.0-linux-amd64.tar.gz
                    type: http
                publish:
                    arch: amd64
                    description: TiDB GA
                    entry_point: bin/tidb-server
                    name: tidb
                    os: linux
                    standalone: false
                    version: v7.5.0
            required:
                - from
                - publish
        RequestMultiarchCollectRequestBody:
            type: object
            properties:
                async:
                    type: boolean
                    description: Whether to run the collection asynchronously. If true, returns a request id. If false or omitted, runs synchronously and returns the result directly.
                    default: false
                    example: true
                image_url:
                    type: string
                    description: The image URL to collect
                    example: Numquam occaecati voluptatibus mollitia in exercitationem nam.
                release_tag_suffix:
                    type: string
                    description: Suffix for the release tag
                    default: release
                    example: Sit sequi.
            example:
                async: true
                image_url: Provident commodi.
                release_tag_suffix: Enim repellendus inventore dolore nisi.
            required:
                - image_url
        RequestMultiarchCollectResponseBody:
            type: object
            properties:
                async:
                    type: boolean
                    description: Whether to run the collection asynchronously. If true, returns a request id. If false or omitted, runs synchronously and returns the result directly.
                    default: false
                    example: true
                repo:
                    type: string
                    description: Repository of the collected image
                    example: Sapiente est vero eveniet.
                request_id:
                    type: string
                    description: Request id for async mode (uuidv4 format)
                    example: 956231c6-4bba-4082-9d8b-b9da5dd6a10b
                    format: uuid
                tags:
                    type: array
                    items:
                        type: string
                        example: Aliquam quo consectetur tempora rerum provident tenetur.
                    description: Tags of the collected image
                    example:
                        - Ut suscipit ea.
                        - Omnis aspernatur et saepe.
            example:
                async: false
                repo: Quaerat soluta quae repudiandae animi est temporibus.
                request_id: 0e3ba708-a180-4c92-8eef-0998c7bc1bfb
                tags:
                    - Possimus aut.
                    - Voluptas accusamus ut et in ut iure.
                    - Earum hic dolorum.
            required:
                - async
        RequestSyncKernelImageRequestBody:
            type: object
            properties:
                image:
                    type: string
                    description: the source container image with tag
                    example: us.gcr.io/pingcap-public/tidbx/tikv:v8.5.4-nextgen.202510.31
                    pattern: ^[a-zA-Z0-9][a-zA-Z0-9._/-]*:[a-zA-Z0-9][a-zA-Z0-9._-]*$
                stage:
                    type: string
                    description: env stage
                    example: dev
                    enum:
                        - dev
                        - prod
            example:
                image: us.gcr.io/pingcap-public/tidbx/tikv:v8.5.4-nextgen.202510.31
                stage: dev
            required:
                - stage
                - image
        RequestToCopyRequestBody:
            type: object
            properties:
                destination:
                    type: string
                    description: destination image url
                    example: Sed enim optio.
                source:
                    type: string
                    description: source image url
                    example: Deserunt laudantium quia nam.
            example:
                destination: In veritatis.
                source: Necessitatibus voluptatem rem aut eaque.
            required:
                - source
                - destination
        RequestToPublishRequestBody:
            type: object
            properties:
                artifact_url:
                    type: string
                    description: The full url of the pushed OCI artifact, contain the tag part. It will parse the repo from it.
                    example: oci.com/repo:tag
                tiup_mirror:
                    type: string
                    description: '`staging` is http://tiup.pingcap.net:8988, `prod` is http://tiup.pingcap.net:8987.'
                    default: staging
                    example: prod
                    enum:
                        - staging
                        - prod
                version:
                    type: string
                    description: Force set the version. Default is the artifact version read from `org.opencontainers.image.version` of the manifest config.
                    example: v1.0.0
            example:
                artifact_url: oci.com/repo:tag
                tiup_mirror: staging
                version: v1.0.0
            required:
                - artifact_url
                - tiup_mirror
        TidbcloudOpsTicket:
            type: object
            properties:
                change_id:
                    type: string
                    description: component publish flow ID
                    example: Voluptas qui earum.
                component:
                    type: string
                    description: component name
                    example: Aut nobis et nostrum dolores dolorem dolorem.
                component_version:
                    type: string
                    description: component version derived from image tag
                    example: Delectus distinctio.
                id:
                    type: string
                    description: ticket ID
                    example: Nihil occaecati occaecati sunt.
                release_id:
                    type: string
                    description: release window ID
                    example: Ratione dolorem qui quaerat.
                url:
                    type: string
                    description: ticket visit url
                    example: http://willmsmetz.org/augustus
                    format: uri
            description: Ops ticket details
            example:
                change_id: Modi consequatur harum laborum reiciendis.
                component: Vero voluptatum magnam.
                component_version: Minus architecto ut suscipit.
                id: Voluptas sit earum.
                release_id: Et consequatur cupiditate quos.
                url: http://heaney.net/jannie
            required:
                - id
                - url
                - component
                - component_version
        TiupDeliveryResults:
            type: object
            properties:
                results:
                    type: object
                    example:
                        prod:
                            - 5f8971d9-ab20-46a7-9d98-f47aa0e129d6
                            - 9869ec3e-50b5-4f09-bb77-d29ab13f4edf
                            - e0f78631-fbaf-4c7b-8ffd-edbb049fdab8
                            - 627d775d-3fbe-4910-bb37-618a03557b4f
                    additionalProperties:
                        type: array
                        items:
                            type: string
                            description: Request id for async mode (uuidv4 format)
                            example: 9ab91a4c-6fed-4fd4-8d80-0ef3c50987b0
                            format: uuid
                        example:
                            - b7275305-76c7-4914-9502-3c8ccfa9c3fb
                            - 12d7235f-2a86-45af-ab21-9c7c4bed8b8a
            example:
                results:
                    prod:
                        - 536e3000-abb4-47be-9474-05132e405f53
                        - 02bd06b9-8ccc-4961-ab79-1f4ce3b3066e
        UpdateComponentVersionInCloudconfigRequestBody:
            type: object
            properties:
                image:
                    type: string
                    description: container image with tag
                    example: xxx.com/component:v26.3.1-nextgen
                stage:
                    type: string
                    description: env stage
                    example: prod
            example:
                image: xxx.com/component:v26.3.1-nextgen
                stage: prod
            required:
                - stage
                - image
        UpdateComponentVersionInCloudconfigResponseBody:
            type: object
            properties:
                stage:
                    type: string
                    example: Facilis fugit.
                tickets:
                    type: array
                    items:
                        $ref: '#/components/schemas/TidbcloudOpsTicket'
                    example:
                        - change_id: Quibusdam quibusdam veniam nisi rerum.
                          component: Omnis autem sequi.
                          component_version: Fuga occaecati.
                          id: Omnis iste ratione doloremque.
                          release_id: Saepe necessitatibus veritatis ipsa qui unde.
                          url: http://glover.biz/corine
                        - change_id: Quibusdam quibusdam veniam nisi rerum.
                          component: Omnis autem sequi.
                          component_version: Fuga occaecati.
                          id: Omnis iste ratione doloremque.
                          release_id: Saepe necessitatibus veritatis ipsa qui unde.
                          url: http://glover.biz/corine
            example:
                stage: Incidunt sed explicabo.
                tickets:
                    - change_id: Quibusdam quibusdam veniam nisi rerum.
                      component: Omnis autem sequi.
                      component_version: Fuga occaecati.
                      id: Omnis iste ratione doloremque.
                      release_id: Saepe necessitatibus veritatis ipsa qui unde.
                      url: http://glover.biz/corine
                    - change_id: Quibusdam quibusdam veniam nisi rerum.
                      component: Omnis autem sequi.
                      component_version: Fuga occaecati.
                      id: Omnis iste ratione doloremque.
                      release_id: Saepe necessitatibus veritatis ipsa qui unde.
                      url: http://glover.biz/corine
                    - change_id: Quibusdam quibusdam veniam nisi rerum.
                      component: Omnis autem sequi.
                      component_version: Fuga occaecati.
                      id: Omnis iste ratione doloremque.
                      release_id: Saepe necessitatibus veritatis ipsa qui unde.
                      url: http://glover.biz/corine
                    - change_id: Quibusdam quibusdam veniam nisi rerum.
                      component: Omnis autem sequi.
                      component_version: Fuga occaecati.
                      id: Omnis iste ratione doloremque.
                      release_id: Saepe necessitatibus veritatis ipsa qui unde.
                      url: http://glover.biz/corine
            required:
                - stage
                - tickets
tags:
    - name: tiup
      description: TiUP Publisher service
    - name: fileserver
      description: 'Publisher service for static file server '
    - name: image
      description: Publisher service for container image
    - name: tidbcloud
      description: Publisher service for tidbcloud platform
